# Generated by Django 3.1.3 on 2020-11-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profileorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='films/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(blank=True, to='app.ActorORM')),
                ('countries', models.ManyToManyField(blank=True, to='app.CountryORM')),
                ('genres', models.ManyToManyField(blank=True, to='app.GenreORM')),
            ],
        ),
    ]
