# Generated by Django 3.1.3 on 2020-11-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_filmorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profileorm')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filmorm')),
            ],
        ),
    ]
